# Configuration using colors from the Set1 palette. Right now the first six are used according to ColorBrewer2
# Colors already approved for dashboard but not used: "#46196b", "#FFE30B"
  
XBB.1.5.X:
  name: "XBB.1.5.X"
  members:
    - "XBB.1.5.X"
  parent: "XBB.X"

XBB.X:
  name: "XBB.X"
  members:
    - "XBB.X"
  color: "#e41a1c"

BQ.1.1.X:
  name: "BQ.1.1.X (Omicron)"
  members:
    - "BQ.1.1.X"
  parent: "BA.5"

BQ.1.X:
  name: "BQ.1.X (Omicron)"
  members:
    - "BQ.1.X"
  parent: "BA.5"

BF.7.X:
  name: "BF.7.X (Omicron)"
  members:
    - "BF.7.X"
  parent: "BA.5"

BA.5:
  name: "BA.5.X (Omicron)"
  members:
    - "BA.5.X"
  color: "#984ea3"

BA.4:
  name: "BA.4.X (Omicron)"
  members:
    - "BA.4.X"
    - "BA.4.6"
  color: "#ff7f00"

BA.2.12.X:
  name: "BA.2.12.X (Omicron)"
  members:
    - "BA.2.12.X"
  parent: "BA.2.X"

BA.2.X:
  name: "BA.2.X (Omicron)"
  members:
    - "BA.2.X"
    - "BN.1.X"
  color: "#4daf4a"

BA.1.1.X:
  name: "BA.1.1.X (Omicron)"
  members:
    - "BA.1.1.X"
  parent: "BA.1"

BA.1:
  name: "BA.1 (Omicron)"
  members:
    - "BA.1"
    - "B.1.1.529"
  color: "#377eb8"

Delta:
  name: "Delta"
  members:
    - "Delta"
  color: "#3b3c3d"
  
  
Recombinants:
  name: "Other recombinants"
  members:
    - "Recombinants"
  color: "#6A6C6E"

Other:
  name: "Other"
  members: null
  color: "#DDDDDD"
